Controllers/GCDataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GCOnline.Models;
using System.IO;

namespace GCOnline.Controllers
{ 
    public class GCDataController : Controller
    {
        private GC_DBContext db = new GC_DBContext();

        public ViewResult Index()
        {
            return View(db.Sequences.ToList());
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file)
        {
            DataModel data = new DataModel();

            data.UploadSequence(file);

            return RedirectToAction("Index");
        }

        public ActionResult GetRuns(FormCollection form)
        {
            List<List<Run>> runList = new List<List<Run>>();
            foreach (var key in form)
            {
                double id = Convert.ToDouble(key);

                var runs = from x in db.Runs
                           where x.SequenceID == id
                           select x;

                List<Run> r = runs.ToList();

                runList.Add(r);
            }

            return View(runList);
        }

        public ViewResult Details(FormCollection form)
        {
            List<Sequence> sequenceList = new List<Sequence>();

            foreach (var key in form)
            {
                double id = Convert.ToDouble(key);

                Sequence sequence = db.Sequences.Find(id);

                sequenceList.Add(sequence);
            }

            return View(sequenceList);
        }

        public ActionResult Delete(FormCollection form)
        {
            List<Sequence> sequenceList = new List<Sequence>();

            foreach (var key in form)
            {
                double id = Convert.ToDouble(key);

                Sequence sequence = db.Sequences.Find(id);

                sequenceList.Add(sequence);
            }

            return View(sequenceList);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(FormCollection form)
        {
            foreach (var key in form)
            {
                double id = Convert.ToDouble(key);

                Sequence sequence = db.Sequences.Find(id);

                db.Sequences.Remove(sequence);

                var runs = from x in db.Runs
                           where x.SequenceID == sequence.SequenceID
                           select x;

                foreach (Run r in runs)
                {
                    db.Runs.Remove(r);
                }

                var peaks = from x in db.Peaks
                            where x.SequenceID == sequence.SequenceID
                            select x;

                foreach (Peak p in peaks)
                {
                    db.Peaks.Remove(p);
                }
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Controllers/QuantificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GCOnline.Models;
using Newtonsoft.Json;
using System.Collections;

namespace GCOnline.Controllers
{
    public class QuantificationController : Controller
    {
        private GC_DBContext db = new GC_DBContext();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            List<Run> runList = new List<Run>();

            DUMP list = new DUMP();

            foreach (var key in form)
            {
                Run newRun = db.Runs.Find(Convert.ToDouble(key));
                //newRun.CDW = newRun.CDW * .6;
                //newRun.SampleVolume = newRun.SampleVolume * .6;
                runList.Add(newRun);
            }

            list.rangeList = db.QuantificationRanges.ToList();

            var caliList = from c in db.Calibrations
                               group c by c.SequenceID into g
                               select g.FirstOrDefault();

            list.runList = runList;
            list.caliList = caliList.ToList();
            
            return View(list);
        }

        public ActionResult SaveQuantification(QuantificationRange range, List<Quantification> quantList)
        {
            DataModel data = new DataModel();

            QuantificationRange r = data.SaveQuantificationRange(range, quantList);

            string json = JsonConvert.SerializeObject(r);

            return Json(json);
        }

        public ActionResult Quantify(List<RunQuantification> runList)
        {
            DataModel data = new DataModel();

            data.SaveRunQuantification(runList);

            return View();
        }
    }
}

Views/GCData/Create.cshtml
@model GCOnline.Models.Sequence

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Sequence</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.SequenceName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SequenceName)
            @Html.ValidationMessageFor(model => model.SequenceName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Uploaded)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Uploaded)
            @Html.ValidationMessageFor(model => model.Uploaded)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/GCData/Delete.cshtml
@model GCOnline.Models.Sequence

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Sequence</legend>

    <div class="display-label">SequenceName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SequenceName)
    </div>

    <div class="display-label">Uploaded</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Uploaded)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/GCData/Details.cshtml
@model GCOnline.Models.Sequence

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Sequence</legend>

    <div class="display-label">SequenceName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SequenceName)
    </div>

    <div class="display-label">Uploaded</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Uploaded)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.SequenceID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/GCData/GetRuns.cshtml
@model IEnumerable<IEnumerable<GCOnline.Models.Run>>

@{
    ViewBag.Title = "GCOnline: Sequence Runs";
}

<h2>Run List for Sequences: </h2>
<ul>
@foreach (var list in Model)
{
    <li>@list.ElementAt(0).SequenceName</li>  
}
 </ul>


<div id="container">

@using (Html.BeginForm("Index", "Quantification", System.Web.Mvc.FormMethod.Post, new { id = "quantify_form", enctype = "multipart/form-data" }))
{
    
    <table class="std_selector">
        <tr>
            <th>
                Run Name
            </th>
            <th>
                Sequence Name
            </th>
            <th>
                <input type="checkbox" onchange="common.selectAll(this)" />
            </th>
        </tr>

    @foreach (var list in Model)
    {
        foreach (var item in list)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RunName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SequenceName)
                </td>
                <td>
                    <input type="checkbox" class="cali_check" value="@Html.DisplayFor(modelItem => item.RunName)" id="@Html.DisplayFor(modelItem => item.RunID)" name="@Html.DisplayFor(modelItem => item.RunID)" />
                </td>
            </tr>
        }
    }
        <tr>
            <td>@Html.ActionLink("Back to List", "Index")</td>
            <td>
                <a href="javascript:void(0)" onclick="common.addtocali()">Create Cali</a>&nbsp;&nbsp;
                <a href="javascript:void(0)" onclick="common.submitQuantification()">Quantify</a>
            </td>
        </tr>
    </table>
    <div class="conc_container"></div>
    <div class="cali_container"></div>
    <div class="standards_container"></div>
    <div class="clear"></div>
}
</div>

Views/GCData/Index.cshtml
@model IEnumerable<GCOnline.Models.Sequence>

@{
    ViewBag.Title = "GCOnline Data Management";
}

<script src="@Url.Content("~/Scripts/sequence.js")" type="text/javascript"></script>

<h2>GCOnline: Data Management</h2>
<p>From here you can manage your GC data:  Upload new sequences, view previously saved sequences and runs, or delete unwated data.</p>

@using (Html.BeginForm("Create", "GCData", System.Web.Mvc.FormMethod.Post, new { enctype="multipart/form-data"})) {
    
    <fieldset>
        <legend>Sequence Upload</legend>

      <input type="file" name="file" id="file" />

      <input type="submit" value="Upload" />
 
    </fieldset>
}

@using (Html.BeginForm("DoSomething", "GCData", System.Web.Mvc.FormMethod.Post, new { id="secondForm" }))
{
    <table>
        <tr>
            <th>
                Sequence Name
            </th>
            <th>
                # of Runs
            </th>
            <th>
                Date Uploaded
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SequenceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfRuns)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Uploaded)
            </td>
            <td>
                <input type="checkbox" id="@Html.DisplayFor(modelItem => item.SequenceID)" name="@Html.DisplayFor(modelItem => item.SequenceID)" class="sequences"/>
            </td>
        </tr>
    }

    </table>
    <div style="margin:5px 0px 0px 191px;">
        <a href="javascript:void(0);" onclick="sequence.submitAction('view')">View Runs</a> |
        <a href="javascript:void(0);" onclick="sequence.submitAction('details')">Details</a> |
        <a href="javascript:void(0);" onclick="sequence.submitAction('delete')">Delete</a> 
    </div>
}